# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

# Ensure the entrypoint is executable
RUN chmod +x dist/index.js

# Start the MCP server (listening on stdio)
CMD ["node", "dist/index.js"]
